fixed shellcheck errors/warnings
TinyToolSH/tsearch pull request #6
Opened 2022-04-12 16:44 UTC by gbgabo

## Description
Fixed all the warnings generated by spellcheck, just like its described on #5 

## Related Issue
closes #5

## Motivation and Context
It focuses on refactoring all scripts to be POSIX compliant. That helps the portability and compatibility of tinytools suite on most platforms.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-04-12 17:12 UTC, Calebe94 requested changes

2022-04-12 17:12 UTC, Calebe94 commented on dmenu_tsearch
>  #!/bin/bash
Change the shebang to `/bin/sh` and run `shellcheck` again.

2022-04-13 01:25 UTC, gbgabo commented on dmenu_tsearch
>  #!/bin/bash
## generated warnings

### for dmenu_tsearch
```sh
Line 21:
    while [ $IS_SPECIAL_INPUT == 1 ]; do
                              ^-- [SC3014](https://github.com/koalaman/shellcheck/wiki/SC3014) (warning): In POSIX sh, == in place of = is undefined.
 
Line 22:
        TERM=$(echo -e "$CLIP_OPTION\n$ENGINE_OPTION\n$PROGRAM_OPTION" | dmenu -p "$PROMPT:" -i)
                    ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
 
Line 25:
                SELECTED_ENGINE=$(echo -e "$ENGINE_CHOICES" | dmenu -p "Engine:" -i -l 10)
                                       ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
 
Line 34:
                SELECTED_PROGRAM=$(echo -e "$PROGRAM_CHOICES" | dmenu -p "Program:" -i)
                                        ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
```

### for search
```sh

Line 26 to 35:
   echo -e "- all search parameters are located in /etc/tinytools/params.yaml"
        ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
 
Line 43:
    local length="${#1}"
    ^-- [SC3043](https://github.com/koalaman/shellcheck/wiki/SC3043) (warning): In POSIX sh, 'local' is undefined.
 
Line 44:
    for (( i = 0; i < length; i++ )); do
    ^-- [SC3005](https://github.com/koalaman/shellcheck/wiki/SC3005) (warning): In POSIX sh, arithmetic for loops are undefined.
                               ^-- [SC3018](https://github.com/koalaman/shellcheck/wiki/SC3018) (warning): In POSIX sh, ++ is undefined.
 
Line 45:
        local c="${1:i:1}"
        ^-- [SC3043](https://github.com/koalaman/shellcheck/wiki/SC3043) (warning): In POSIX sh, 'local' is undefined.
                 ^-- [SC3057](https://github.com/koalaman/shellcheck/wiki/SC3057) (warning): In POSIX sh, string indexing is undefined.
 
Line 60:
            echo -e "$($search_params -k "$1")"
                 ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
 
Line 63:
            echo -e "$($search_params -v "$1")"
                 ^-- [SC3037](https://github.com/koalaman/shellcheck/wiki/SC3037) (warning): In POSIX sh, echo flags are undefined.
 
Line 83:
        echo "${query/TERM/$term}"
              ^-- [SC3060](https://github.com/koalaman/shellcheck/wiki/SC3060) (warning): In POSIX sh, string replacement is undefined.
```

lot of more stuff to change lol

just committed a fix for all these errors @Calebe94

2022-04-14 13:09 UTC, Calebe94 approved these changes
OK

2022-04-14 13:10 UTC, merged